apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
spec:
  selector:
    app: flask-backend
  ports:
    - protocol: TCP
      port: 5000 # The port the service will expose
      targetPort: 5000 # The port on the container to forward traffic to
  type: ClusterIP