apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
  labels:
    app: react-frontend-service
spec:
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 5173 # The port the service will expose
      targetPort: 80 # The port on the container to forward traffic to
  type: LoadBalancer