apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
  labels:
    app: node-backend-service
spec:
  selector:
    app: node-backend
  ports:
    - name: http
      protocol: TCP
      port: 3000 # The port the service will expose
      targetPort: 3000 # The port on the container to forward traffic to
  type: ClusterIP